<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/*
@Author: Habibur Rahman <240217006@aston.ac.uk>
@Description: This is a seeder to seed the products table with specific products for each category
*/
class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        // Get Category IDs
        $foodId = DB::table('categories')->where('category_name', 'Food')->value('category_id');
        $toysId = DB::table('categories')->where('category_name', 'Toys')->value('category_id');
        $accessoriesId = DB::table('categories')->where('category_name', 'Accessories')->value('category_id');
        $healthcareId = DB::table('categories')->where('category_name', 'Healthcare')->value('category_id');
        $clothingId = DB::table('categories')->where('category_name', 'Clothing')->value('category_id');

        $products = [
            // 1. FOOD (5 items)
            [
                'category_id' => $foodId,
                'product_name' => 'Premium Dog Kibble',
                'description' => 'High-protein dry food for adult dogs.',
                'price' => 25.99,
                'stock_quantity' => 50,
                'image_url' => null,
                'brand' => 'PawPerfect',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Salmon Cat Paté',
                'description' => 'Smooth salmon paté rich in Omega-3.',
                'price' => 2.50,
                'stock_quantity' => 100,
                'image_url' => null,
                'brand' => 'PurrfectCatch',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Hamster Muesli Mix',
                'description' => 'Crunchy muesli mix with seeds and nuts.',
                'price' => 6.50,
                'stock_quantity' => 40,
                'image_url' => null,
                'brand' => 'SmallPaws',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Tropical Fish Flakes',
                'description' => 'Color-enhancing flakes for tropical fish.',
                'price' => 8.99,
                'stock_quantity' => 60,
                'image_url' => null,
                'brand' => 'AquaLife',
                'pet_type' => 'Fish',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Parrot Fruit & Nut Blend',
                'description' => 'Exotic fruit and nut mix for large birds.',
                'price' => 14.50,
                'stock_quantity' => 30,
                'image_url' => null,
                'brand' => 'TropicalWings',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 2. TOYS (5 items)
            [
                'category_id' => $toysId,
                'product_name' => 'Rubber Chew Bone',
                'description' => 'Durable rubber bone for aggressive chewers.',
                'price' => 9.99,
                'stock_quantity' => 45,
                'image_url' => null,
                'brand' => 'ToughToy',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Feather Wand Teaser',
                'description' => 'Interactive wand toy with feathers and bells.',
                'price' => 5.99,
                'stock_quantity' => 80,
                'image_url' => null,
                'brand' => 'CatPlay',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Hamster Exercise Wheel',
                'description' => 'Silent spinner wheel for hamsters.',
                'price' => 12.00,
                'stock_quantity' => 25,
                'image_url' => null,
                'brand' => 'RunFast',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Bird Mirror & Bell',
                'description' => 'Hanging mirror with a bell for cage entertainment.',
                'price' => 4.50,
                'stock_quantity' => 50,
                'image_url' => null,
                'brand' => 'BirdieFun',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Squeaky Plush Duck',
                'description' => 'Soft plush toy with an internal squeaker.',
                'price' => 7.50,
                'stock_quantity' => 60,
                'image_url' => null,
                'brand' => 'SoftPaws',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 3. ACCESSORIES (5 items)
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Leather Dog Collar',
                'description' => 'Premium leather collar with brass buckle.',
                'price' => 18.00,
                'stock_quantity' => 40,
                'image_url' => null,
                'brand' => 'LuxePet',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Cat Scratching Post',
                'description' => 'Sisal-wrapped scratching post with base.',
                'price' => 24.99,
                'stock_quantity' => 20,
                'image_url' => null,
                'brand' => 'ScratchMaster',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Aquarium Castle Decor',
                'description' => 'Resin castle decoration for fish tanks.',
                'price' => 15.50,
                'stock_quantity' => 35,
                'image_url' => null,
                'brand' => 'AquaDecor',
                'pet_type' => 'Fish',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Hamster Water Bottle',
                'description' => 'No-drip water bottle with mounting bracket.',
                'price' => 5.00,
                'stock_quantity' => 100,
                'image_url' => null,
                'brand' => 'ThirstyPet',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Bird Cage Cover',
                'description' => 'Darkening cover for restful sleep.',
                'price' => 11.00,
                'stock_quantity' => 30,
                'image_url' => null,
                'brand' => 'NightNight',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 4. HEALTHCARE (5 items)
            [
                'category_id' => $healthcareId,
                'product_name' => 'Flea & Tick Shampoo',
                'description' => 'Medicated shampoo to repel fleas and ticks.',
                'price' => 12.99,
                'stock_quantity' => 50,
                'image_url' => null,
                'brand' => 'PestFree',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Cat Multivitamins',
                'description' => 'Daily chewable vitamins for feline health.',
                'price' => 9.50,
                'stock_quantity' => 80,
                'image_url' => null,
                'brand' => 'VitaCat',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Fish Tank Water Conditioner',
                'description' => 'Makes tap water safe for fish.',
                'price' => 6.00,
                'stock_quantity' => 100,
                'image_url' => null,
                'brand' => 'AquaSafe',
                'pet_type' => 'Fish',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Bird Mite Spray',
                'description' => 'Gentle spray to control mites on birds.',
                'price' => 8.00,
                'stock_quantity' => 40,
                'image_url' => null,
                'brand' => 'AvianCare',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Hamster Vitamin Drops',
                'description' => 'Liquid vitamins to add to water.',
                'price' => 5.50,
                'stock_quantity' => 60,
                'image_url' => null,
                'brand' => 'SmallVits',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 5. CLOTHING (5 items)
            [
                'category_id' => $clothingId,
                'product_name' => 'Waterproof Dog Raincoat',
                'description' => 'Yellow raincoat with reflective strips.',
                'price' => 22.00,
                'stock_quantity' => 25,
                'image_url' => null,
                'brand' => 'DryDog',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Cat Bow Tie',
                'description' => 'Cute adjustable bow tie for cats.',
                'price' => 4.00,
                'stock_quantity' => 100,
                'image_url' => null,
                'brand' => 'FancyFeline',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Dog Christmas Sweater',
                'description' => 'Festive knit sweater for the holidays.',
                'price' => 18.50,
                'stock_quantity' => 0, // Sold out test
                'image_url' => null,
                'brand' => 'CozyPaws',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Bandana Set (3-Pack)',
                'description' => 'Set of 3 colorful bandanas.',
                'price' => 9.00,
                'stock_quantity' => 50,
                'image_url' => null,
                'brand' => 'StylePup',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Small Pet Harness',
                'description' => 'Soft harness for rabbits or large hamsters.',
                'price' => 10.00,
                'stock_quantity' => 30,
                'image_url' => null,
                'brand' => 'SafeWalk',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
