<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/*
@Author: Habibur Rahman <240217006@aston.ac.uk>
@Description: This is a seeder to seed the products table with specific products for each category
*/
class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        // Get Category IDs
        $foodId = DB::table('categories')->where('category_name', 'Food')->value('category_id');
        $toysId = DB::table('categories')->where('category_name', 'Toys')->value('category_id');
        $accessoriesId = DB::table('categories')->where('category_name', 'Accessories')->value('category_id');
        $healthcareId = DB::table('categories')->where('category_name', 'Healthcare')->value('category_id');
        $clothingId = DB::table('categories')->where('category_name', 'Clothing')->value('category_id');

        $products = [
            // 1. FOOD (5 items)
            [
                'category_id' => $foodId,
                'product_name' => 'Premium Dog Kibble',
                'description' => 'High-protein dry food for adult dogs.',
                'price' => 25.99,
                'stock_quantity' => 50,
                'image_url' => 'https://cdn.petsathome.com/public/images/products/900_P801.jpg',
                'brand' => 'PetsAtHome',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Salmon Cat Paté',
                'description' => 'Smooth salmon paté rich in Omega-3.',
                'price' => 2.50,
                'stock_quantity' => 100,
                'image_url' => 'https://m.media-amazon.com/images/I/81unP1XJOyL.jpg',
                'brand' => 'Purina',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Hamster Muesli Mix',
                'description' => 'Crunchy muesli mix with seeds and nuts.',
                'price' => 6.50,
                'stock_quantity' => 40,
                'image_url' => 'https://images.onlinepets.com/product-images/catalog/738076399ebcd50a9c82334ff7bd6c1b54014523871da46b866fb58d02161176_3.jpeg',
                'brand' => 'Versele Laga',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Tropical Fish Flakes',
                'description' => 'Color-enhancing flakes for tropical fish.',
                'price' => 8.99,
                'stock_quantity' => 60,
                'image_url' => 'https://digitalcontent.api.tesco.com/v2/media/ghs/5ee6ef0e-0dac-4755-9276-eb890e2b235a/8c1b83c7-f3a4-40f7-b42c-6e05de64ab7f_230306372.jpeg',
                'brand' => 'Aquarian',
                'pet_type' => 'Fish',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $foodId,
                'product_name' => 'Parrot Fruit & Nut Blend',
                'description' => 'Exotic fruit and nut mix for large birds.',
                'price' => 14.50,
                'stock_quantity' => 30,
                'image_url' => 'https://cdn11.bigcommerce.com/s-bbbdf/images/stencil/original/products/1197/3318/johnsons_jeff_fruit_nut_veg_mix__59974.1700467830.jpg?',
                'brand' => 'Johnsons & Jeff',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 2. TOYS (5 items)
            [
                'category_id' => $toysId,
                'product_name' => 'Rubber Chew Bone',
                'description' => 'Durable rubber bone for aggressive chewers.',
                'price' => 9.99,
                'stock_quantity' => 45,
                'image_url' => 'https://www.petscorner.co.uk/Images/Product/Default/xlarge/benebone-bone.jpg',
                'brand' => 'BeneBones',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Feather Wand Teaser',
                'description' => 'Interactive wand toy with feathers and bells.',
                'price' => 5.99,
                'stock_quantity' => 80,
                'image_url' => 'https://www.webbox.co.uk/wp-content/uploads/2021/10/A73983-DRWO864536BNA-WBX-Festive-Feather-Wand-Backboard-864536BN-WHITE-3D.webp',
                'brand' => 'Webbox',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Hamster Exercise Wheel',
                'description' => 'Silent spinner wheel for hamsters.',
                'price' => 12.00,
                'stock_quantity' => 25,
                'image_url' => 'https://cdn.omlet.com/images/catalog/2024/07/03/hamster-wheel-with-stand-designed-by-omlet.jpg',
                'brand' => 'Omlet',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Bird Mirror & Bell',
                'description' => 'Hanging mirror with a bell for cage entertainment.',
                'price' => 4.50,
                'stock_quantity' => 50,
                'image_url' => 'https://m.media-amazon.com/images/I/61aisZffgrL._AC_UF1000,1000_QL80_.jpg',
                'brand' => 'Hypeety',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $toysId,
                'product_name' => 'Squeaky Plush Duck',
                'description' => 'Soft plush toy with an internal squeaker.',
                'price' => 7.50,
                'stock_quantity' => 60,
                'image_url' => 'https://m.media-amazon.com/images/I/710W+sDlrgL.jpg',
                'brand' => 'SZKOKUHO',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 3. ACCESSORIES (5 items)
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Leather Dog Collar',
                'description' => 'Premium leather collar with brass buckle.',
                'price' => 18.00,
                'stock_quantity' => 40,
                'image_url' => 'https://www.dogsandco.com/wp-content/uploads/2023/04/Purple-Collar-Sq-scaled.jpg',
                'brand' => 'DogsAndCo',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Cat Scratching Post',
                'description' => 'Sisal-wrapped scratching post with base.',
                'price' => 24.99,
                'stock_quantity' => 20,
                'image_url' => 'https://cdn.omlet.com/images/catalog/2023/02/17/cat-climbing-tall-stak-cat-scratcher-square.jpg',
                'brand' => 'Omlet',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Aquarium Castle Decor',
                'description' => 'Resin castle decoration for fish tanks.',
                'price' => 15.50,
                'stock_quantity' => 35,
                'image_url' => 'https://www.midlandwaterlife.com/wp-content/uploads/2022/03/36752.png',
                'brand' => 'MidlandWaterLife',
                'pet_type' => 'Fish',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Hamster Water Bottle',
                'description' => 'No-drip water bottle with mounting bracket.',
                'price' => 5.00,
                'stock_quantity' => 100,
                'image_url' => 'https://cdn.omlet.com/images/originals/716_-_bottle.jpg',
                'brand' => 'Omlet',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $accessoriesId,
                'product_name' => 'Bird Cage Cover',
                'description' => 'Darkening cover for restful sleep.',
                'price' => 11.00,
                'stock_quantity' => 30,
                'image_url' => 'https://cdn.omlet.com/images/originals/geo-vogelkaefig-abdeckung-im-luxus-design-nachthimmel-mobil.jpg',
                'brand' => 'Omlet',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 4. HEALTHCARE (5 items)
            [
                'category_id' => $healthcareId,
                'product_name' => 'Flea & Tick Shampoo',
                'description' => 'Medicated shampoo to repel fleas and ticks.',
                'price' => 12.99,
                'stock_quantity' => 50,
                'image_url' => 'https://cdn.petsathome.com/public/images/products/900_7148365.jpg',
                'brand' => 'Pets at Home',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Cat Multivitamins',
                'description' => 'Daily chewable vitamins for feline health.',
                'price' => 9.50,
                'stock_quantity' => 80,
                'image_url' => 'https://images.onlinepets.com/product-images/catalog/XmlXMJoXM5it6XTCVUnePUyEuQhnok-metaUHVyaW5hLVByby1QbGFuLU11bHRpdml0YW1pbnMtS2F0LmpwZw==-.jpg',
                'brand' => 'Purina',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Fish Tank Water Conditioner',
                'description' => 'Makes tap water safe for fish.',
                'price' => 6.00,
                'stock_quantity' => 100,
                'image_url' => 'https://m.media-amazon.com/images/I/61CfCuTeE3L.jpg',
                'brand' => 'API',
                'pet_type' => 'Fish',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Bird Mite Spray',
                'description' => 'Gentle spray to control mites on birds.',
                'price' => 8.00,
                'stock_quantity' => 40,
                'image_url' => 'https://www.petscorner.co.uk/Images/Product/Default/large/johnsons_bird_antimite_spray_extra_150ml_xl.jpg',
                'brand' => 'Johnsons',
                'pet_type' => 'Bird',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $healthcareId,
                'product_name' => 'Hamster Vitamin Drops',
                'description' => 'Liquid vitamins to add to water.',
                'price' => 5.50,
                'stock_quantity' => 60,
                'image_url' => 'https://m.media-amazon.com/images/I/51SL3R5L0KL.jpg',
                'brand' => 'Johnsons',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],

            // 5. CLOTHING (5 items)
            [
                'category_id' => $clothingId,
                'product_name' => 'Waterproof Dog Raincoat',
                'description' => 'Yellow raincoat with reflective strips.',
                'price' => 22.00,
                'stock_quantity' => 25,
                'image_url' => 'https://www.treatyourdog.co.uk/cdn/shop/files/purple-waterproof-dog-coat_1000x1000.jpg?v=1701953085',
                'brand' => 'DryDog',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Cat Bow Tie',
                'description' => 'Cute adjustable bow tie for cats.',
                'price' => 4.00,
                'stock_quantity' => 100,
                'image_url' => 'https://www.nogginsandbinkles.com/cdn/shop/products/Blue_cat_bow_tie_luxury_vegan_cork_leather_1200x1200.jpg?v=1683132076',
                'brand' => 'FancyFeline',
                'pet_type' => 'Cat',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Dog Sweater',
                'description' => 'Cosy Dog Sweater',
                'price' => 18.50,
                'stock_quantity' => 0, // Sold out test
                'image_url' => 'https://www.snazzydot.co.uk/media/img/shop/srcpd/000819.jpg',
                'brand' => 'CozyPaws',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Bandana Set (3-Pack)',
                'description' => 'Set of 3 colorful bandanas.',
                'price' => 9.00,
                'stock_quantity' => 50,
                'image_url' => 'https://millbryhill.co.uk/cdn/shop/files/340635-4.jpg?v=1740585684&width=1080',
                'brand' => 'StylePup',
                'pet_type' => 'Dog',
                'date_added' => now(),
                'is_active' => 1,
            ],
            [
                'category_id' => $clothingId,
                'product_name' => 'Small Pet Harness',
                'description' => 'Soft harness for rabbits or large hamsters.',
                'price' => 10.00,
                'stock_quantity' => 30,
                'image_url' => 'https://www.hugglepets.co.uk/wp-content/uploads/2018/02/Trixie-Small-Animal-Mesh-Harness-Lead-Set-2.jpg',
                'brand' => 'SafeWalk',
                'pet_type' => 'Hamster',
                'date_added' => now(),
                'is_active' => 1,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
